package: mediapool3_demo
version: '1.1.0'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO

page:
    title: 'Medienpool via API'
    icon: rex-icon fa-photo-film
    subpages:
        demo:
            title: 'Demo'
            icon: rex-icon fa-play
        debug:
            title: 'Debug'
            icon: rex-icon fa-bug
            perm: admin

requires:
    redaxo: '>=5.10'
    php:
        version: '>=7.4'
    packages:
        api: '>=1.0'
